config/routes.rb
Rails.application.routes.draw do

  get 'pages/about'

  root 'pages#index'

  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: :true
  validates :city, presence: :true
  validates :latitude, presence: :true
  validates :longitude, presence: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @users = User.all
    @user = User.new
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: "User was successfully created." }
      else
        format.html { redirect_to root_path, notice: "User not created." }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'User was successfully destroyed.' }
    end
  end


  private

    def user_params
      params.require(:user).permit(:name, :city, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bootstrap_helper.rb
module BootstrapHelper
  def bootstrap_class_for(flash_type)
    case flash_type
    when 'success'
      'alert-success'
    when 'error'
      'alert-danger'
    when 'alert'
      'alert-warning'
    when 'notice'
      'alert-success'
    else
      flash_type.to_s
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "MAPS", root_path, class: 'navbar-brand' %>
    </div>
    <ul class="nav navbar-nav navbar-right">
        <li class="active"><%= link_to "Index", '#' %></li>
        <li><%= link_to "About", pages_about_path %></li>
      </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MapsExample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDG-I4LxfH9WUGpEN3XdlByMoRHz-AZzJA&signed_in=true&libraries=places&callback=initAutocomplete" defer></script>
</head>
<body>

<div id="wrapper">
  <div id="page-wrapper">
    <div class="col-xs-offset-2 col-xs-8">
      <%= render 'layouts/header' %>
      <div class="panel panel-default">
        <div class="panel-body">
          <%= render partial: '/shared/messages' %>

          <%= yield %>
        </div>
      </div>
    </div>
  </div>
</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About this application</h1>

<p>There is some information about this test application</p>

app/views/pages/index.html.erb
<h1>Please enter your direction</h1>

<form>
  <fieldset class="form-group">
    <label>Address:</label>
    <input type="text" class="form-control" id="autocompleteGoogle"/>
    <small class="text-muted" id="searchResultsGoogle">Please enter your address in format <b>Street, City, Country</b>.</small>
  </fieldset>
</form>

<div id="saveResultGoogle" style="display: none">
  <%= simple_form_for @user do |f| %>
    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :latitude, :as => :hidden,
        :input_html => {
          :id => "addressLatitudeGoogle"
        } %>
      <%= f.input :longitude, :as => :hidden,
        :input_html => {
          :id => "addressLongitudeGoogle"
        } %>
      <%= f.input :city, :as => :hidden,
        :input_html => {
          :id => "cityGoogle"
          } %>
    </div>
    <div class="form-inputs">
    <%= f.button :submit, class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

<hr>

<table class="table">
  <thead>
    <tr>
    <th><span>User</span></th>
    <th><span>City</span></th>
    <th><span>Created</span></th>
    <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |u| %>
      <%= render :partial => 'users/user', locals: { user: u } %>
    <% end %>
  </tbody>
</table>

app/views/shared/_messages.html.erb
<% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> fade in" role="alert">
      <button class="close" data-dismiss="alert">×</button>
      <%= message %>
    </div>
<% end %>

app/views/users/_user.html.erb
<tr>
  <td>
    <%= user.name %>
  </td>
  <td>
    <%= user.city %>
  </td>
  <td>
    <%= user.created_at.strftime("%d/%m/%Y") %>
  </td>
  <td>
    <%= link_to "Delete", user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %>
  </td>
</tr>